# Generated by Django 5.0.4 on 2024-04-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmu_classified_app', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(max_length=500, upload_to='ads/', verbose_name='Image'),
        ),
    ]
